create extension if not exists pgcrypto;

create table if not exists public.product_categories (
  id uuid primary key default gen_random_uuid(),
  collection text not null check (collection in ('gateau', 'menu')),
  name text not null,
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_categories_collection_name_key unique (collection, name)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'products_collection_legacy_id_key'
  ) then
    alter table public.products
      add constraint products_collection_legacy_id_key unique (collection, legacy_id);
  end if;
end $$;

insert into public.product_categories
  (collection, name, sort_order, is_active)
values
  ('menu', 'PETIT DÉJEUNER', 1, true),
  ('menu', 'FORMULE', 15, true),
  ('menu', 'COCKTAIL', 18, true),
  ('menu', 'MILKSHAKE', 23, true),
  ('menu', 'BOISSONS SPECIALS', 29, true),
  ('menu', 'BOISSONS CHAUDE', 38, true),
  ('menu', 'JUS', 47, true),
  ('menu', 'DEJEUNER', 55, true),
  ('menu', 'GAUFFRES', 63, true),
  ('menu', 'PANCAKES', 71, true),
  ('menu', 'CREPE SUCREE', 80, true),
  ('menu', 'CREPES SALES', 92, true),
  ('menu', 'SODA', 98, true),
  ('menu', 'SUPLEMENT', 101, true)
on conflict (collection, name) do update set
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();

insert into public.products
  (legacy_id, collection, category, name, description, image_url, price, is_promo, is_new, is_active, sort_order)
values
  (1, 'menu', 'PETIT DÉJEUNER', 'EXPRESS', 'Boisson chaude · Jus d''orange · viennoiserie · Bouteille d''eau', 'images/petitdej/express.webp', 28, false, false, true, 1),
  (2, 'menu', 'PETIT DÉJEUNER', 'HOLLANDAIS', 'Boisson chaude · Jus d''orange · Salade · 2 Toast oeuf au fromage · Charcutrie · Bouteille d''eau', 'images/petitdej/holondais.webp', 45, false, false, true, 2),
  (3, 'menu', 'PETIT DÉJEUNER', 'FASSI', 'Boisson chaude · Jus d''orange · 2 oeuf avec khlie · Huile d''olive , olive · Panier de pain · Bouteille d''eau', 'images/petitdej/fassi.webp', 45, false, false, true, 3),
  (4, 'menu', 'PETIT DÉJEUNER', 'nature', 'Boisson chaude · Jus d''orange · 2 oeuf avec khlie · Huile d''olive , olive · Panier de pain · Bouteille d''eau', 'images/petitdej/fassi.webp', 35, false, false, true, 4),
  (5, 'menu', 'PETIT DÉJEUNER', 'traditionel', 'Boisson chaude · Jus d''orange · 2 oeuf avec khlie · Huile d''olive , olive · Panier de pain · Bouteille d''eau', 'images/petitdej/fassi.webp', 38, false, false, true, 5),
  (6, 'menu', 'PETIT DÉJEUNER', 'chamali', 'Boisson chaude · Jus d''orange · 2 oeuf avec khlie · Huile d''olive , olive · Panier de pain · Bouteille d''eau', 'images/petitdej/fassi.webp', 46, false, false, true, 6),
  (7, 'menu', 'PETIT DÉJEUNER', 'crock mr', 'Boisson chaude · Jus d''orange · 2 oeuf avec khlie · Huile d''olive , olive · Panier de pain · Bouteille d''eau', 'images/petitdej/fassi.webp', 62, false, false, true, 7),
  (8, 'menu', 'PETIT DÉJEUNER', 'kids', 'Boisson chaude · Jus d''orange · 2 oeuf avec khlie · Huile d''olive , olive · Panier de pain · Bouteille d''eau', 'images/petitdej/fassi.webp', 38, false, false, true, 8),
  (9, 'menu', 'PETIT DÉJEUNER', 'TOAST FROMAGE', 'fromage', 'images/petitdej/toastf.webp', 15, false, false, true, 9),
  (10, 'menu', 'PETIT DÉJEUNER', 'TOAST FROMAGE CHARCUTERIE', 'Fromage · Charcuterie', 'images/petitdej/toastfc..webp', 18, false, false, true, 10),
  (11, 'menu', 'PETIT DÉJEUNER', 'OMELETTES NATURE', 'nature', 'images/petitdej/omelettesn.webp', 17, true, false, true, 11),
  (12, 'menu', 'PETIT DÉJEUNER', 'OMELETTES FROMAGE', 'Fromage', 'images/petitdej/omelettesf.webp', 19, false, false, true, 12),
  (13, 'menu', 'PETIT DÉJEUNER', 'OMELETTES FROMAGE ET CHARCUTERIE', 'Fromage · Charcuterie', 'images/petitdej/omelettesch.webp', 22, false, false, true, 13),
  (14, 'menu', 'PETIT DÉJEUNER', 'OMELETTES KHLIE', 'Khlie', 'images/petitdej/omeletteskh.webp', 25, false, false, true, 14),
  (15, 'menu', 'FORMULE', 'FORMULE 1', '· Omelette fromage · panier de pain · baby pancakes nutella · boisson chaude · Bouteille d''eau ·', 'images/petitdej/express.webp', 35, false, false, true, 15),
  (16, 'menu', 'FORMULE', 'FORMULE 2', '· croissant salé · baby pancakes nutella · boisson chaude · bouteille d''eau ·', 'images/petitdej/holondais.webp', 43, false, false, true, 16),
  (17, 'menu', 'FORMULE', 'FORMULE 3', '· mini crepe poulet · gauffre nutella · Boisson chaude · Bouteille d''eau ·', 'images/petitdej/fassi.webp', 49, false, false, true, 17),
  (18, 'menu', 'COCKTAIL', 'MOJITO PASSION', 'Fruits de passion', 'images/cocktail/fruispa.webp', 28, false, false, true, 18),
  (19, 'menu', 'COCKTAIL', 'MOJITO VERGIN', 'Mojito virgin', 'images/cocktail/virgin.webp', 25, false, false, true, 19),
  (20, 'menu', 'COCKTAIL', 'MOJITO FRUITS ROUGE', 'Fruits rouge', 'images/cocktail/fruitro.webp', 28, false, false, true, 20),
  (21, 'menu', 'COCKTAIL', 'SPRING BLUE MOJITO', 'SPRING BLUE', 'images/cocktail/SPRINGBLUEMOJITO.WEBP', 45, false, false, true, 21),
  (22, 'menu', 'COCKTAIL', 'PINA COLADA', 'Pina colada', 'images/cocktail/pina.webp', 28, false, false, true, 22),
  (23, 'menu', 'MILKSHAKE', 'MILKSHAKE CARAMEL', 'CARAMEL', 'images/MILKSHAKE/MILKSHAKECARAMEL.webp', 28, false, false, true, 23),
  (24, 'menu', 'MILKSHAKE', 'MILKSHAKE FRAISE', 'FRAISE', 'images/MILKSHAKE/MILKSHAKEFRAISE.webp', 28, false, false, true, 24),
  (25, 'menu', 'MILKSHAKE', 'MILKSHAKE CHOCOLAT', 'chocolat', 'images/MILKSHAKE/MILKSHAKECHOCOLAT.webp', 28, false, true, true, 25),
  (26, 'menu', 'MILKSHAKE', 'milkshake vanille', 'vanille', 'images/MILKSHAKE/milkshakevanille.webp', 28, false, false, true, 26),
  (27, 'menu', 'MILKSHAKE', 'MILKSHAKE OREO', '', 'images/MILKSHAKE/MILKSHAKEOERO.webp', 30, true, false, true, 27),
  (28, 'menu', 'MILKSHAKE', 'MILKSHAKE KITKAT', 'KITKAT', 'images/MILKSHAKE/KITKAT.webp', 30, false, false, true, 28),
  (29, 'menu', 'BOISSONS SPECIALS', 'ICETEA PEACH', 'PEACH', 'images/BOISSONS SPECIALS/ice tea peach.webp', 25, false, false, true, 29),
  (30, 'menu', 'BOISSONS SPECIALS', 'ICETEA LEMON', '', 'images/BOISSONS SPECIALS/ice tea lemon.webp', 25, true, false, true, 30),
  (31, 'menu', 'BOISSONS SPECIALS', 'ICETEA MANGO-ANANAS', 'MANGO-ANANAS', 'images/BOISSONS SPECIALS/ice tea mango ananas.webp', 25, false, false, true, 31),
  (32, 'menu', 'BOISSONS SPECIALS', 'ICE COFFEE', 'caramel . chocolat .vanille', 'images/BOISSONS SPECIALS/ICE CARAMEL COFFEE.WEBP', 25, false, false, true, 32),
  (33, 'menu', 'BOISSONS SPECIALS', 'MATCHA LATTE', 'LATTE', 'images/BOISSONS SPECIALS/MATCHA LATTE.webp', 34, false, true, true, 33),
  (34, 'menu', 'BOISSONS SPECIALS', 'ESPRESSO MATCHA', 'ESPRESSO', 'images/BOISSONS SPECIALS/espresso matcha.webp', 36, false, false, true, 34),
  (35, 'menu', 'BOISSONS SPECIALS', 'COCONUT MATCHA', 'COCONUT', 'images/BOISSONS SPECIALS/coconut matcha.webp', 38, false, false, true, 35),
  (36, 'menu', 'BOISSONS SPECIALS', 'STRAWBERRY MATCHA', 'STRAWBERRY', 'images/BOISSONS SPECIALS/strawberry matcha.webp', 38, false, false, true, 36),
  (37, 'menu', 'BOISSONS SPECIALS', 'MANGUE MATCHA', 'MANGUE', 'images/BOISSONS SPECIALS/mangue matcha.webp', 38, false, false, true, 37),
  (38, 'menu', 'BOISSONS CHAUDE', 'EXPRESSO', '', 'images/BOISSON/EXPESSO.webp', 12, false, false, true, 38),
  (39, 'menu', 'BOISSONS CHAUDE', 'cafe allonge', 'cafe allonge', 'images/BOISSON/cafe allonge.webp', 14, false, false, true, 39),
  (40, 'menu', 'BOISSONS CHAUDE', 'CAFE CREME', 'CAFE CREME', 'images/BOISSON/CAFE CREME.webp', 16, false, false, true, 40),
  (41, 'menu', 'BOISSONS CHAUDE', 'DOUBLE EXPRESSO', '', 'images/BOISSON/DOUBLEEXPRESSO.webp', 14, true, false, true, 41),
  (42, 'menu', 'BOISSONS CHAUDE', 'CAFE NES NES', 'CAFE · LAIT', 'images/BOISSON/CAFENESNES.webp', 16, false, false, true, 42),
  (43, 'menu', 'BOISSONS CHAUDE', 'CHOCOLAT CHAUD', 'CHOCOLAT CHAUD', 'images/BOISSON/CHOCOLATCHAUD.webp', 18, false, false, true, 43),
  (44, 'menu', 'BOISSONS CHAUDE', 'CAPPUCCINO', 'CAPPUCCINO', 'images/BOISSON/CAPPUCCINO.webp', 22, false, false, true, 44),
  (45, 'menu', 'BOISSONS CHAUDE', 'the a la monthe', 'the a la monthe', 'images/BOISSON/thealamonthe.webp', 14, false, false, true, 45),
  (46, 'menu', 'BOISSONS CHAUDE', 'CHOCOLAT FONDUE', 'CHOCOLAT FONDUE', 'images/BOISSON/chocolat fondue.webp', 25, false, false, true, 46),
  (47, 'menu', 'JUS', 'JUS ORANGE', '', 'images/jus/jusdorange.webp', 20, false, false, true, 47),
  (48, 'menu', 'JUS', 'JUS DE BANANE', 'cafe allonge', 'images/jus/banane.webp', 20, false, false, true, 48),
  (49, 'menu', 'JUS', 'JUS DE POMME', 'POMME', 'images/jus/pomme.webp', 20, false, false, true, 49),
  (50, 'menu', 'JUS', 'JUS DE FRAISE', '', 'images/jus/fraise.webp', 25, true, false, true, 50),
  (51, 'menu', 'JUS', 'JUS D''AVOCAT', 'AVOCAT', 'images/jus/AVOCAT.webp', 30, false, false, true, 51),
  (52, 'menu', 'JUS', 'JUS DE MANGUE', 'MANGUE', 'images/jus/mangue.webp', 30, false, false, true, 52),
  (53, 'menu', 'JUS', 'JUS D''ANANAS', 'ANANAS', 'images/jus/ananas.webp', 30, false, false, true, 53),
  (54, 'menu', 'JUS', 'JUS PANACHE', 'PANACHE', 'images/jus/panache.webp', 30, false, false, true, 54),
  (55, 'menu', 'DEJEUNER', 'PANINI KHLIE', 'KHLIE', 'images/DEJEUNER/PANINI MIXTE.WEBP', 20, false, true, true, 55),
  (56, 'menu', 'DEJEUNER', 'PANINI CHARCUTERIE', 'CHARCUTERIE', 'images/DEJEUNER/PANINI CHARCUTERIE.WEBP', 20, false, false, true, 56),
  (57, 'menu', 'DEJEUNER', 'PANINI POULET', '', 'images/DEJEUNER/PANINI POULET.WEBP', 22, true, false, true, 57),
  (58, 'menu', 'DEJEUNER', 'PANINI VIANDE HACHE', 'VIANDE HACHE', 'images/DEJEUNER/PANINI VIANDE HACHE.WEBP', 25, false, false, true, 58),
  (59, 'menu', 'DEJEUNER', 'PANINI MIXTE', 'MIXTE', 'images/DEJEUNER/PANINI MIXTE.WEBP', 26, false, true, true, 59),
  (60, 'menu', 'DEJEUNER', 'SANDWICH POULET', 'POULET', 'images/DEJEUNER/TACOS POULET.WEBP', 28, false, false, true, 60),
  (61, 'menu', 'DEJEUNER', 'SANDWICH VIANDE HACHE', 'VIANDE HACHE', 'images/DEJEUNER/TACOS VIANDE HACHE.WEBP', 28, false, false, true, 61),
  (62, 'menu', 'DEJEUNER', 'SANDWICH CRISPY', 'CRISPY', 'images/DEJEUNER/TACOS MIXTE.WEBP', 28, false, false, true, 62),
  (63, 'menu', 'GAUFFRES', 'GAUFFRE NATURE', 'NATURE', 'images/GAUFRES-PANCAKES/GAUFRE NATURE.WEBP', 18, false, false, true, 63),
  (64, 'menu', 'GAUFFRES', 'GAUFFRE AMLOU', '', 'images/GAUFRES-PANCAKES/GAUFRE AMLOU.WEBP', 24, true, false, true, 64),
  (65, 'menu', 'GAUFFRES', 'GAUFFRE MIEL FRUITS SEC', 'MIEL FRUITS SEC', 'images/GAUFRES-PANCAKES/GAUFRE MIEL FRUITS SEC.WEBP', 27, false, false, true, 65),
  (66, 'menu', 'GAUFFRES', 'GAUFFRE CARAMEL BEURRE SALE', 'CARAMEL SALTY BUTTER', 'images/GAUFRES-PANCAKES/GAUFRE CARAMEL BEURRE SALE.WEBP', 27, false, true, true, 66),
  (67, 'menu', 'GAUFFRES', 'GAUFFRE NUTELLA', 'NUTELLA', 'images/GAUFRES-PANCAKES/GAUFRE NUTELLA.WEBP', 26, false, false, true, 67),
  (68, 'menu', 'GAUFFRES', 'GAUFFRE NUTELLA BANANE', 'NUTELLA BANANE', 'images/GAUFRES-PANCAKES/GAUFRE NUTELLA BANANE.WEBP', 29, false, false, true, 68),
  (69, 'menu', 'GAUFFRES', 'GAUFFRE LOTUS', 'LOTUS', 'images/GAUFRES-PANCAKES/GAUFRE LOTUS.WEBP', 32, false, false, true, 69),
  (70, 'menu', 'GAUFFRES', 'GAUFFRE FRUIT DE SAISON', 'FRUIT DE SAISON', 'images/GAUFRES-PANCAKES/GAUFRE FRUIT DE SAISON.WEBP', 34, false, false, true, 70),
  (71, 'menu', 'PANCAKES', 'PANCAKES NATURE', 'NATURE', 'images/GAUFRES-PANCAKES/PANCAKES NATURE.WEBP', 18, false, false, true, 71),
  (72, 'menu', 'PANCAKES', 'PANCAKES AMLOU', '', 'images/GAUFRES-PANCAKES/PANCAKES AMLOU.WEBP', 24, true, false, true, 72),
  (73, 'menu', 'PANCAKES', 'PANCAKES MIEL FRUITS SEC', 'PANCAKES MIEL FRUITS SEC', 'images/GAUFRES-PANCAKES/PANCAKES MIEL FRUITS SEC.WEBP', 27, false, false, true, 73),
  (74, 'menu', 'PANCAKES', 'PANCAKES CARAMEL BEURRE SALE', 'CARAMEL SALTY BUTTER', 'images/GAUFRES-PANCAKES/PANCAKES CARAMEL BEURRE SALE.WEBP', 27, false, true, true, 74),
  (75, 'menu', 'PANCAKES', 'PANCAKES NUTELLA', 'NUTELLA', 'images/GAUFRES-PANCAKES/PANCAKES NUTELLA.WEBP', 26, false, false, true, 75),
  (76, 'menu', 'PANCAKES', 'PANCAKES NUTELLA BANANE', 'NUTELLA BANANE', 'images/GAUFRES-PANCAKES/PANCAKES NUTELLA BANANE.WEBP', 29, false, false, true, 76),
  (77, 'menu', 'PANCAKES', 'PANCAKES LOTUS', 'LOTUS', 'images/GAUFRES-PANCAKES/PANCAKES LOTUS.WEBP', 32, false, false, true, 77),
  (78, 'menu', 'PANCAKES', 'PANCAKES FRUIT DE SAISON', 'FRUIT DE SAISON', 'images/GAUFRES-PANCAKES/PANCAKES FRUIT DE SAISON.WEBP', 34, false, false, true, 78),
  (79, 'menu', 'PANCAKES', 'PANCAKES PISTACHE', 'PISTACHE', 'images/GAUFRES-PANCAKES/PANCAKES PISTACHE.WEBP', 35, false, false, true, 79),
  (80, 'menu', 'CREPE SUCREE', 'CREPE NATURE', 'NATURE', 'images/CREPE/CREPE NATURE.WEBP', 15, false, false, true, 80),
  (81, 'menu', 'CREPE SUCREE', 'CREPE KITKAT', '', 'images/CREPE/CREPE KITKAT.WEBP', 32, true, false, true, 81),
  (82, 'menu', 'CREPE SUCREE', 'CREPE MIEL FRUITS SEC', 'CREPE MIEL FRUITS SEC', 'images/CREPE/CREPE MIEL FRUITS SEC.WEBP', 22, false, false, true, 82),
  (83, 'menu', 'CREPE SUCREE', 'CREPE CARAMEL BEURRE SALE', 'CARAMEL BEURRE SALE', 'images/CREPE/CREPE CARAMEL BEURRE SALE.WEBP', 27, false, true, true, 83),
  (84, 'menu', 'CREPE SUCREE', 'CREPE NUTELLA', 'NUTELLA', 'images/CREPE/CREPE NUTELLA.WEBP', 26, false, false, true, 84),
  (85, 'menu', 'CREPE SUCREE', 'CREPE NUTELLA BANANE', 'NUTELLA BANANE', 'images/CREPE/CREPE NUTELLA BANANE.WEBP', 29, false, false, true, 85),
  (86, 'menu', 'CREPE SUCREE', 'CREPE LOTUS', 'LOTUS', 'images/CREPE/CREPE LOTUS.WEBP', 34, false, false, true, 86),
  (87, 'menu', 'CREPE SUCREE', 'CREPE FRUIT DE SAISON', 'FRUIT DE SAISON', 'images/CREPE/CREPE FRUIT DE SAISON.WEBP', 35, false, false, true, 87),
  (88, 'menu', 'CREPE SUCREE', 'CREPE OREO', 'OREO', 'images/CREPE/CREPE OREO.WEBP', 32, false, false, true, 88),
  (89, 'menu', 'CREPE SUCREE', 'CREPE KINDER BUENO', 'KINDER BUENO', 'images/CREPE/CREPE KINDER BUENO.WEBP', 34, false, false, true, 89),
  (90, 'menu', 'CREPE SUCREE', 'CREPE KUNAFA PISTACHE', 'KUNAFA PISTACHE', 'images/CREPE/CREPE KUNAFA PISTACHE.WEBP', 35, false, false, true, 90),
  (91, 'menu', 'CREPE SUCREE', 'CREPE MONDE GOURMAND', 'KITKAT, OREO, PEPITE', 'images/pat/crepemondegourmand.webp', 39, false, false, true, 91),
  (92, 'menu', 'CREPES SALES', 'CREPE FROMAGE', 'FROMAGE', 'images/CREPE/CREPE FROMAGE.WEBP', 25, false, false, true, 92),
  (93, 'menu', 'CREPES SALES', 'CREPE CHARCUTERIE FROMAGE', 'CHARCUTERIE FROMAGE', 'images/CREPE/CREPE CHARCUTERIE FROMAGE.WEBP', 28, false, false, true, 93),
  (94, 'menu', 'CREPES SALES', 'CREPE POULET CHAMPIGNON', 'POULET CHAMPIGNON', 'images/CREPE/CREPE POULET CHAMPIGNON.WEBP', 30, false, false, true, 94),
  (95, 'menu', 'CREPES SALES', 'CREPE POULET', 'POULET', 'images/CREPE/CREPE POULET.WEBP', 32, false, false, true, 95),
  (96, 'menu', 'CREPES SALES', 'CREPE VIANDE HACHEE BOEUF', 'VIANDE HACHEE BOEUF', 'images/CREPE/CREPE VIANDE HACHEE BOEUF.WEBP', 35, false, false, true, 96),
  (97, 'menu', 'CREPES SALES', 'CREPE MIXTE', 'MIXTE', 'images/CREPE/CREPE MIXTE.WEBP', 34, false, false, true, 97),
  (98, 'menu', 'SODA', 'EAU MINERALE', '', 'images/soda/eau.webp', 8, false, false, true, 98),
  (99, 'menu', 'SODA', 'SODA CANETTE 25CL', 'SODA CANETTE 25CL', 'images/soda/soda.webp', 14, false, false, true, 99),
  (100, 'menu', 'SODA', 'OULMES', 'OULMES', 'images/soda/oulmes.webp', 14, false, false, true, 100),
  (101, 'menu', 'SUPLEMENT', 'JBEN OU CHARCUTERIE', '', 'images/x.webp', 4, false, false, true, 101),
  (102, 'menu', 'SUPLEMENT', 'MIEL OU HUILE D OLIVE', 'MIEL OU HUILE D OLIVE', 'images/x.webp', 3, false, false, true, 102),
  (103, 'menu', 'SUPLEMENT', 'FRITE', 'FRITE', 'images/frites.webp', 8, false, false, true, 103)
on conflict (collection, legacy_id) do update set
  category = excluded.category,
  name = excluded.name,
  description = excluded.description,
  image_url = excluded.image_url,
  price = excluded.price,
  is_promo = excluded.is_promo,
  is_new = excluded.is_new,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  updated_at = now();
